POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRvbW15IiwiaWQiOiI2MmRkOTQ1OGVmZTlhMmI3ZjJiMDdjYjQiLCJpYXQiOjE2NTg4NjE1MjEsImV4cCI6MTY1ODg2NTEyMX0.uDIPu9lxM9rFlK5Bx_l8mgXpyXZOuAWNhbb28F9x68Q

{
    "title": "Blaha",
    "author": "Tommy",
    "url": "www.yayay.com", 
    "userId": "62dd9458efe9a2b7f2b07cb4"
}